services:
  web:
    build: .
    container_name: portfolio_web_dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./static:/app/static
      - ./templates:/app/templates
      - ./data:/app/data  # For SQLite database
    env_file:
      - .env
    networks:
      - portfolio_network_dev
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Optional: Redis for caching (even in dev)
  redis:
    image: redis:7-alpine
    container_name: portfolio_redis_dev
    ports:
      - "6379:6379"
    networks:
      - portfolio_network_dev
    restart: unless-stopped
    profiles:
      - cache

networks:
  portfolio_network_dev:
    driver: bridge
