version: '3.8'

services:
  web:
    build: .
    container_name: portfolio_web
    ports:
      - "6000:8000"
    volumes:
      - .:/app
      - ./static:/app/static
      - ./templates:/app/templates
    env_file:
      - .env
    networks:
      - portfolio_network
    restart: unless-stopped

networks:
  portfolio_network:
    driver: bridge
