version: '3.8'

services:
  web:
    build: .
    container_name: portfolio_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./static:/app/static
      - ./templates:/app/templates
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - portfolio_network
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: portfolio_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - portfolio_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: portfolio_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - portfolio_network
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:

networks:
  portfolio_network:
    driver: bridge
